/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.13
 * Generated at: 2023-11-21 16:43:17 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.util.*;

public final class user_005fedit_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPではGET、POST、またはHEADのみが許可されます。 JasperはOPTIONSも許可しています。");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath() );
      out.write("/css/user_edit.css\">\n");
      out.write("<link href=\"https://use.fontawesome.com/releases/v6.2.0/css/all.css\" rel=\"stylesheet\">\n");
      out.write("<script src=\"https://ajax.aspnetcdn.com/ajax/jQuery/jquery-3.3.1.min.js\"></script>\n");
      out.write("<script src=\"");
      out.print(request.getContextPath() );
      out.write("/js/user_edit.js\"></script>\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("    <head>\n");
      out.write("        <meta http-equiv=\"Content-Type\" content=\"text/html\" charset=\"UTF-8\">\n");
      out.write("        <title>JavaApp</title>\n");
      out.write("    </head>\n");
      out.write("\n");
      out.write("\n");
      out.write("    <body>\n");
      out.write("      <!-- リクエストスコープからログインユーザーのIDを取得する -->\n");
      out.write("      ");
String name = (String)session.getAttribute("name");
      out.write("\n");
      out.write("      ");
String address = (String)session.getAttribute("address");
      out.write("\n");
      out.write("      ");
String job = (String)session.getAttribute("job");
      out.write("\n");
      out.write("\n");
      out.write("      <header id=\"header\">\n");
      out.write("        <h3 class=\"logo\"><a href=\"#\">Java Portfolio</a></h3>\n");
      out.write("        <nav>\n");
      out.write("          <ul class=\"nav__list\">\n");
      out.write("            <li class=\"nav__item\"><a href=\"user\">プロフィール</a></li>\n");
      out.write("            <li class=\"nav__item\"><a href=\"search\">さがす</a></li>\n");
      out.write("            <li class=\"nav__item\"><a href=\"setting\">各種設定</a></li>\n");
      out.write("            <li class=\"nav__item\"><a href=\"logout\">ログアウト</a></li>\n");
      out.write("          </ul>\n");
      out.write("        </nav>\n");
      out.write("      </header>\n");
      out.write("\n");
      out.write("      <div style=\"margin-top:120px;\" class=\"box_con\">\n");
      out.write("\n");
      out.write("        <form>\n");
      out.write("            <table class=\"formTable\">\n");
      out.write("            <h1 style=\"margin-bottom: 10px;\">基本情報</h1>\n");
      out.write("              <tr>\n");
      out.write("                <tr>\n");
      out.write("                  <th>ニックネーム</th>\n");
      out.write("                  <td>\n");
      out.write("                    <div class=\"box\">\n");
      out.write("                      ");
 if(name != null){ 
      out.write("\n");
      out.write("                        ");
      out.print( name );
      out.write("\n");
      out.write("                      ");
 }else if(name == null){ 
      out.write("\n");
      out.write("                        <p>未設定</p>\n");
      out.write("                      ");
 } 
      out.write("\n");
      out.write("                      \n");
      out.write("                    </div>\n");
      out.write("                  </td>\n");
      out.write("                </tr>\n");
      out.write("                <th>居住地</th>\n");
      out.write("                <td>\n");
      out.write("                  <select name=\"address\" id=\"user_address\">\n");
      out.write("                    <option value=\"\">未設定</option>\n");
      out.write("                    <option value=\"大阪\">大阪</option>\n");
      out.write("                    <option value=\"兵庫\">兵庫</option>\n");
      out.write("                    <option value=\"京都\">京都</option>\n");
      out.write("                    <option value=\"奈良\">奈良</option>\n");
      out.write("                    <option value=\"和歌山\">和歌山</option>\n");
      out.write("                \n");
      out.write("                  </select>\n");
      out.write("                </td>\n");
      out.write("              </tr>\n");
      out.write("              <tr>\n");
      out.write("                <th>職業</th>\n");
      out.write("                  <td>\n");
      out.write("                    <select name=\"job\" id=\"user_job\">\n");
      out.write("                      <option value=\"\">未設定</option>\n");
      out.write("                      <option value=\"エンジニア\">エンジニア</option>\n");
      out.write("                      <option value=\"薬剤師\">薬剤師</option>\n");
      out.write("                      <option value=\"研究職\">美容師</option>\n");
      out.write("                      <option value=\"医師\">医師</option>\n");
      out.write("                      <option value=\"デザイナー\">デザイナー</option>\n");
      out.write("                  </select>\n");
      out.write("                  </td>\n");
      out.write("              </tr>\n");
      out.write("              \n");
      out.write("              </table>\n");
      out.write("          </form>\n");
      out.write("        </div>\n");
      out.write("    </body>\n");
      out.write("</html>\n");
      out.write("\n");
      out.write("<script>\n");
      out.write("\n");
      out.write("  \n");
      out.write("\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("\n");
      out.write("<style>\n");
      out.write(".box {\n");
      out.write("  border: 2px solid #aaa;\n");
      out.write("  padding: 5px;\n");
      out.write("  color:#4e4f52;\n");
      out.write("  display: flex;\n");
      out.write("  justify-content: space-between;\n");
      out.write("}\n");
      out.write("\n");
      out.write("html {\n");
      out.write("  overflow-y: scroll;\n");
      out.write("}\n");
      out.write("body,div,dl,dt,dd,ul,ol,li,h1,h2,h3,h4,h5,h6,pre,form,fieldset,input,textarea,p,blockquote,th,td {\n");
      out.write("  margin: 0;\n");
      out.write("  padding: 0;\n");
      out.write("}\n");
      out.write("address,caption,cite,code,dfn,em,strong,th,var {\n");
      out.write("  font-style: normal;\n");
      out.write("}\n");
      out.write("table {\n");
      out.write("  border-collapse: collapse;\n");
      out.write("  border-spacing: 0;\n");
      out.write("}\n");
      out.write("caption,th {\n");
      out.write("  text-align: left;\n");
      out.write("}\n");
      out.write("q:before,q:after {\n");
      out.write("  content: '';\n");
      out.write("}\n");
      out.write("object,embed {\n");
      out.write("  vertical-align: top;\n");
      out.write("}\n");
      out.write("hr,legend {\n");
      out.write("  display: none;\n");
      out.write("}\n");
      out.write("h1{\n");
      out.write("  color:#2b2b2a;\n");
      out.write("  font-size: 30px;\n");
      out.write("}\n");
      out.write("img,abbr,acronym,fieldset {\n");
      out.write("  border: 0;\n");
      out.write("}\n");
      out.write("li {\n");
      out.write("  list-style-type: none;\n");
      out.write("}\n");
      out.write("sup {\n");
      out.write("  vertical-align: super;\n");
      out.write("  font-size: 0.5em;\n");
      out.write("}\n");
      out.write("img {\n");
      out.write("  vertical-align: top;\n");
      out.write("}\n");
      out.write("i {\n");
      out.write("  font-style: normal;\n");
      out.write("}\n");
      out.write("/*----リセットcss*----/\n");
      out.write("\n");
      out.write("/*デザインcss↓*/\n");
      out.write(".box_con {\n");
      out.write("  max-width: 600px;\n");
      out.write("  margin: 0  auto;\n");
      out.write("}\n");
      out.write("@media only screen and (max-width: 768px) {\n");
      out.write("  .box_con {\n");
      out.write("    width: 95%;\n");
      out.write("  }\n");
      out.write("}\n");
      out.write(".box_con form {\n");
      out.write("  width: 100%;\n");
      out.write("}\n");
      out.write(".box_con form table {\n");
      out.write("  width: 100%;\n");
      out.write("}\n");
      out.write(".box_con form table tr {\n");
      out.write("  position: relative;\n");
      out.write("}\n");
      out.write(".box_con form table tr:after {\n");
      out.write("  content: \"\";\n");
      out.write("  position: absolute;\n");
      out.write("  width: 100%;\n");
      out.write("  left: 0;\n");
      out.write("  bottom: 0;\n");
      out.write("  height: 1px;\n");
      out.write("  border-bottom: dotted #cdcdcd 1px;\n");
      out.write("}\n");
      out.write(".box_con form table tr th {\n");
      out.write("  width: 30%;\n");
      out.write("  font-weight: normal;\n");
      out.write("  padding: 1em .5em;\n");
      out.write("  -moz-box-sizing: border-box;\n");
      out.write("  -webkit-box-sizing: border-box;\n");
      out.write("  box-sizing: border-box;\n");
      out.write("}\n");
      out.write("@media only screen and (max-width: 768px) {\n");
      out.write("  .box_con form table tr th {\n");
      out.write("    text-align: center;\n");
      out.write("    width: 100%;\n");
      out.write("    display: block;\n");
      out.write("    background: #97ae88;\n");
      out.write("    padding: .8em .2em;\n");
      out.write("    color: #fff;\n");
      out.write("  }\n");
      out.write("}\n");
      out.write(".box_con form table tr th span {\n");
      out.write("  background: #cd6f55;\n");
      out.write("  padding: 0 .3em;\n");
      out.write("  color: #fff;\n");
      out.write("  margin-left: .5em;\n");
      out.write("  -moz-box-sizing: border-box;\n");
      out.write("  -webkit-box-sizing: border-box;\n");
      out.write("  box-sizing: border-box;\n");
      out.write("}\n");
      out.write(".box_con form table tr td {\n");
      out.write("  padding: 1em .5em;\n");
      out.write("  -moz-box-sizing: border-box;\n");
      out.write("  -webkit-box-sizing: border-box;\n");
      out.write("  box-sizing: border-box;\n");
      out.write("}\n");
      out.write("@media only screen and (max-width: 768px) {\n");
      out.write("  .box_con form table tr td {\n");
      out.write("    padding: 1.5em .5em;\n");
      out.write("    display: block;\n");
      out.write("    width: 100%;\n");
      out.write("  }\n");
      out.write("}\n");
      out.write(".box_con form table tr .box_br {\n");
      out.write("  display: block;\n");
      out.write("}\n");
      out.write(".box_con form table tr select {\n");
      out.write("  border: 1px solid #97ae88;\n");
      out.write("}\n");
      out.write(".box_con form table tr label input {\n");
      out.write("  cursor: pointer;\n");
      out.write("  display: none;\n");
      out.write("  vertical-align: middle;\n");
      out.write("}\n");
      out.write(".box_con form table tr .radio02-input + label {\n");
      out.write("  padding-left: 23px;\n");
      out.write("  margin-right: 20px;\n");
      out.write("  position: relative;\n");
      out.write("}\n");
      out.write(".box_con form table tr .radio02-input + label:before {\n");
      out.write("  content: \"\";\n");
      out.write("  display: block;\n");
      out.write("  position: absolute;\n");
      out.write("  top: 50%;\n");
      out.write("  left: 0;\n");
      out.write("  width: 16px;\n");
      out.write("  height: 16px;\n");
      out.write("  border: 1px solid #999;\n");
      out.write("  border-radius: 50%;\n");
      out.write("  -moz-transform: translateY(-50%);\n");
      out.write("  -ms-transform: translateY(-50%);\n");
      out.write("  -webkit-transform: translateY(-50%);\n");
      out.write("  transform: translateY(-50%);\n");
      out.write("}\n");
      out.write(".box_con form table tr .radio02-input:checked + label:after {\n");
      out.write("  content: \"\";\n");
      out.write("  display: block;\n");
      out.write("  position: absolute;\n");
      out.write("  top: 50%;\n");
      out.write("  left: 3px;\n");
      out.write("  width: 12px;\n");
      out.write("  height: 12px;\n");
      out.write("  background: #97ae88;\n");
      out.write("  border-radius: 50%;\n");
      out.write("  -moz-transform: translateY(-50%);\n");
      out.write("  -ms-transform: translateY(-50%);\n");
      out.write("  -webkit-transform: translateY(-50%);\n");
      out.write("  transform: translateY(-50%);\n");
      out.write("}\n");
      out.write(".box_con form table tr select, .box_con form table tr input, .box_con form table tr textarea {\n");
      out.write("  width: 100%;\n");
      out.write("  height: 3em;\n");
      out.write("  padding: .5em;\n");
      out.write("  -moz-box-sizing: border-box;\n");
      out.write("  -webkit-box-sizing: border-box;\n");
      out.write("  box-sizing: border-box;\n");
      out.write("}\n");
      out.write(".box_con form table tr textarea {\n");
      out.write("  height: 10em;\n");
      out.write("}\n");
      out.write("\n");
      out.write("/*プライバシーのデザインcss↓*/\n");
      out.write(".con_pri {\n");
      out.write("  max-width: 700px;\n");
      out.write("  margin: 0  auto;\n");
      out.write("}\n");
      out.write("@media only screen and (max-width: 768px) {\n");
      out.write("  .con_pri {\n");
      out.write("    width: 95%;\n");
      out.write("  }\n");
      out.write("}\n");
      out.write(".con_pri .box_pri {\n");
      out.write("  height: 300px;\n");
      out.write("  overflow-y: scroll;\n");
      out.write("  border: 1px solid #cdcdcd;\n");
      out.write("  background: #f7f7f7;\n");
      out.write("  -moz-box-sizing: border-box;\n");
      out.write("  -webkit-box-sizing: border-box;\n");
      out.write("  box-sizing: border-box;\n");
      out.write("  margin-top: 20px;\n");
      out.write("  padding: 20px 55px;\n");
      out.write("}\n");
      out.write("@media only screen and (max-width: 768px) {\n");
      out.write("  .con_pri .box_pri {\n");
      out.write("    margin-top: 4%;\n");
      out.write("    padding: 3%;\n");
      out.write("  }\n");
      out.write("}\n");
      out.write("@media only screen and (min-width: 769px) and (max-width: 1024px) {\n");
      out.write("  .con_pri .box_pri {\n");
      out.write("    padding: 4%;\n");
      out.write("  }\n");
      out.write("}\n");
      out.write(".con_pri .box_pri .box_tori {\n");
      out.write("  text-align: left;\n");
      out.write("  margin-top: 40px;\n");
      out.write("}\n");
      out.write("@media only screen and (max-width: 768px) {\n");
      out.write("  .con_pri .box_pri .box_tori {\n");
      out.write("    margin-top: 4%;\n");
      out.write("  }\n");
      out.write("}\n");
      out.write(".con_pri .box_pri .box_tori h4 {\n");
      out.write("  font-weight: normal;\n");
      out.write("  margin-bottom: 30px;\n");
      out.write("  font-size: 150%;\n");
      out.write("}\n");
      out.write("@media only screen and (max-width: 768px) {\n");
      out.write("  .con_pri .box_pri .box_tori h4 {\n");
      out.write("    margin-bottom: 4%;\n");
      out.write("  }\n");
      out.write("}\n");
      out.write(".con_pri .box_pri .box_tori .txt {\n");
      out.write("  padding: 0 20px;\n");
      out.write("}\n");
      out.write("@media only screen and (max-width: 768px) {\n");
      out.write("  .con_pri .box_pri .box_tori .txt {\n");
      out.write("    padding: 0;\n");
      out.write("  }\n");
      out.write("}\n");
      out.write(".con_pri .box_pri .box_num {\n");
      out.write("  margin-top: 30px;\n");
      out.write("}\n");
      out.write("@media only screen and (max-width: 768px) {\n");
      out.write("  .con_pri .box_pri .box_num {\n");
      out.write("    margin-top: 5%;\n");
      out.write("  }\n");
      out.write("}\n");
      out.write(".con_pri .box_pri .box_num h4 {\n");
      out.write("  font-weight: normal;\n");
      out.write("  font-size: 113%;\n");
      out.write("}\n");
      out.write(".con_pri .box_pri .box_num .txt {\n");
      out.write("  padding: 10px 0 0 20px;\n");
      out.write("}\n");
      out.write("@media only screen and (max-width: 768px) {\n");
      out.write("  .con_pri .box_pri .box_num .txt {\n");
      out.write("    padding: 3% 0 0 3%;\n");
      out.write("  }\n");
      out.write("}\n");
      out.write("\n");
      out.write(".box_check {\n");
      out.write("  text-align: center;\n");
      out.write("  margin: 1em auto;\n");
      out.write("}\n");
      out.write(".box_check label {\n");
      out.write("  display: inline-block;\n");
      out.write("}\n");
      out.write(".box_check label span {\n");
      out.write("  margin-left: .3em;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".btn {\n");
      out.write("  text-align: center;\n");
      out.write("}\n");
      out.write(".btn input {\n");
      out.write("  display: inline-block;\n");
      out.write("  background: #eee;\n");
      out.write("  padding: .5em 4em;\n");
      out.write("  color: #000;\n");
      out.write("  text-decoration: none;\n");
      out.write("  cursor: pointer;\n");
      out.write("  border: none;\n");
      out.write("  -moz-transition: all 0.4s;\n");
      out.write("  -o-transition: all 0.4s;\n");
      out.write("  -webkit-transition: all 0.4s;\n");
      out.write("  transition: all 0.4s;\n");
      out.write("}\n");
      out.write(".btn input:hover {\n");
      out.write("  filter: progid:DXImageTransform.Microsoft.Alpha(Opacity=70);\n");
      out.write("  opacity: 0.7;\n");
      out.write("}\n");
      out.write("</style>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
